// Generated by @mdxe/fumadocs - DO NOT EDIT
import { type Config, defineConfig } from 'waku/config'
import mdx from 'fumadocs-mdx/vite'
import * as MdxConfig from './source.config'
import tailwindcss from '@tailwindcss/vite'
import tsconfigPaths from 'vite-tsconfig-paths'
import type { UserConfig } from 'vite'

export default defineConfig({
  unstable_adapter: 'waku/adapters/cloudflare',
  vite: {
    plugins: [tailwindcss(), mdx(MdxConfig), tsconfigPaths()],
  } satisfies UserConfig as Config['vite'],
})
