// Static asset worker - generated by @mdxe/do
export default {
  async fetch(request, env) {
    const url = new URL(request.url)
    let path = url.pathname

    // Serve index.html for root
    if (path === '/' || path === '') {
      path = '/index.html'
    }

    // Try to serve from assets
    const asset = env.ASSETS?.get?.(path) || env.__STATIC_CONTENT?.[path]
    if (asset) {
      const contentType = getContentType(path)
      return new Response(asset, {
        headers: { 'Content-Type': contentType }
      })
    }

    // 404
    return new Response('Not Found', { status: 404 })
  }
}

function getContentType(path) {
  const ext = path.split('.').pop()?.toLowerCase()
  const types = {
    html: 'text/html',
    css: 'text/css',
    js: 'application/javascript',
    json: 'application/json',
    png: 'image/png',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    gif: 'image/gif',
    svg: 'image/svg+xml',
    ico: 'image/x-icon',
  }
  return types[ext] || 'application/octet-stream'
}