// Generated by @mdxe/fumadocs - DO NOT EDIT
import type { BaseLayoutProps } from 'fumadocs-ui/layouts/shared'
import { GithubIcon } from 'lucide-react'

export function baseOptions(): BaseLayoutProps {
  return {
    nav: {
      title: 'beads-workflows',
    },
    links: [
      {
        text: 'GitHub',
        url: 'https://github.com/dot-do/beads-workflows',
        icon: <GithubIcon className="size-4" />,
        external: true,
      },
    ],
  }
}
